In [ ]:
import numpy as np
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
B = np.array([[1,0,0], [0,1,0], [0,0,1]])
C = A+B
C

array([[ 2,  2,  3],
       [ 4,  6,  6],
       [ 7,  8, 10]])

In [ ]:
vector = np.array([1,2,3])
res = np.dot(C, vector)
res

array([15, 34, 53])

In [ ]:
transpon = C.T
transpon

array([[ 2,  4,  7],
       [ 2,  6,  8],
       [ 3,  6, 10]])

In [ ]:
inverse_matrix = np.linalg.inv(C)
inverse_matrix

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

In [ ]:
#Задание 2
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [ ]:
result_values, result_vectors = np.linalg.eig(m)
print("Собственные значения:")
print(result_values)
print("\nСобственные векторы:")
print(result_vectors)

Собственные значения:
[1. 4.]

Собственные векторы:
[[-0.89442719 -0.70710678]
 [ 0.4472136  -0.70710678]]


In [ ]:
#Задание 3
G = np.array([[1, 1],[2, 3]])
determinant = np.linalg.det(G)

print("Определитель матрицы G:", determinant)

Определитель матрицы G: 1.0
